name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run:
          echo "$PRIVATE_KEY" > secret_key
          chmod 600 secret_key
          ssh -oStrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i secret_key
          cd /var/www/kadai-tutorial
      - name: git pull
        run:
          git pull origin master  
